import type {
  Property,
  PropertyRiskProfile,
  InsuranceCostEstimate,
  InsurabilityStatus,
  CarriersResult,
  PropertyPublicData,
} from '@coverguard/shared'

const DUMMY_ID = 'demo-sample-property'

export const dummyProperty: Property = {
  id: DUMMY_ID,
  address: '742 Evergreen Terrace',
  city: 'Springfield',
  state: 'IL',
  zip: '62704',
  county: 'Sangamon',
  lat: 39.7817,
  lng: -89.6501,
  propertyType: 'SINGLE_FAMILY',
  yearBuilt: 1995,
  squareFeet: 2150,
  bedrooms: 4,
  bathrooms: 2.5,
  lotSize: 0.28,
  estimatedValue: 385000,
  lastSalePrice: 340000,
  lastSaleDate: '2021-06-15',
  parcelId: '15-28-300-012',
  createdAt: '2024-01-01T00:00:00Z',
  updatedAt: '2024-01-01T00:00:00Z',
}

export const dummyRiskProfile: PropertyRiskProfile = {
  propertyId: DUMMY_ID,
  overallRiskLevel: 'MODERATE',
  overallRiskScore: 42,
  flood: {
    level: 'LOW',
    score: 18,
    trend: 'STABLE',
    description: 'Property is outside the Special Flood Hazard Area with minimal historical flood events.',
    details: [
      'FEMA Flood Zone X (minimal flood hazard)',
      'No flood claims recorded in the past 20 years',
      'Elevation is 8 ft above the nearest base flood elevation',
    ],
    dataSource: 'FEMA National Flood Hazard Layer',
    lastUpdated: '2024-12-01T00:00:00Z',
    floodZone: 'X',
    firmPanelId: '17167C0225E',
    baseFloodElevation: null,
    inSpecialFloodHazardArea: false,
    annualChanceOfFlooding: 0.2,
  },
  fire: {
    level: 'LOW',
    score: 12,
    trend: 'STABLE',
    description: 'Low wildfire risk due to suburban setting and proximity to fire services.',
    details: [
      'Not in a Wildland-Urban Interface zone',
      'Nearest fire station is 1.3 miles away',
      'Low vegetation density in surrounding area',
    ],
    dataSource: 'USFS Wildland-Urban Interface / Cal Fire FHSZ',
    lastUpdated: '2024-12-01T00:00:00Z',
    fireHazardSeverityZone: null,
    wildlandUrbanInterface: false,
    nearestFireStation: 1.3,
    vegetationDensity: 'Low',
  },
  wind: {
    level: 'MODERATE',
    score: 45,
    trend: 'STABLE',
    description: 'Moderate wind risk with occasional severe thunderstorms and tornado activity.',
    details: [
      'Design wind speed: 115 mph (ASCE 7-22)',
      'Located in Tornado Alley region',
      'Moderate hail risk based on historical data',
    ],
    dataSource: 'ASCE 7 Wind Speed Maps / NOAA SLOSH',
    lastUpdated: '2024-12-01T00:00:00Z',
    designWindSpeed: 115,
    hurricaneRisk: false,
    tornadoRisk: true,
    hailRisk: true,
  },
  earthquake: {
    level: 'HIGH',
    score: 68,
    trend: 'STABLE',
    description: 'Elevated seismic risk due to proximity to the New Madrid Seismic Zone.',
    details: [
      'Within 120 miles of the New Madrid Seismic Zone',
      'Soil type: Class D (Stiff Soil)',
      'Moderate liquefaction potential in some areas',
    ],
    dataSource: 'USGS Seismic Design Maps (ASCE 7-22)',
    lastUpdated: '2024-12-01T00:00:00Z',
    seismicZone: 'New Madrid Seismic Zone',
    nearestFaultLine: 120,
    soilType: 'Class D — Stiff Soil',
    liquefactionPotential: 'MODERATE',
  },
  crime: {
    level: 'MODERATE',
    score: 38,
    trend: 'IMPROVING',
    description: 'Crime rates are slightly below the national average with an improving trend.',
    details: [
      'Violent crime index: 32 (national avg: 47)',
      'Property crime index: 44 (national avg: 51)',
      'Crime rates have decreased 8% over the past 3 years',
    ],
    dataSource: 'FBI Crime Data Explorer',
    lastUpdated: '2024-12-01T00:00:00Z',
    violentCrimeIndex: 32,
    propertyCrimeIndex: 44,
    nationalAverageDiff: -12,
  },
  heat: {
    level: 'MODERATE',
    score: 32,
    trend: 'WORSENING',
    description: 'Moderate heat risk with projected increase in extreme heat days due to climate change in central Illinois.',
    details: [
      'Average of 5–7 days per year exceeding 100°F',
      'Projected to increase to 12–15 days by 2050 (RCP 4.5)',
      'Urban heat island effect: 1.5–2°F above rural areas',
      'Cooling infrastructure adequate but aging in some areas',
    ],
    dataSource: 'NOAA Climate Data / IPCC Projections',
    lastUpdated: '2024-12-01T00:00:00Z',
    extremeHeatDays: 6,
    projectedHeatDays2050: 14,
    urbanHeatIslandEffect: 1.8,
    coolingInfrastructureDeficit: false,
  },
  drought: {
    level: 'LOW',
    score: 35,
    trend: 'STABLE',
    description: 'Low-to-moderate drought risk with stable conditions. Illinois has reliable precipitation and minimal drought severity historically.',
    details: [
      'Palmer Drought Severity Index: −0.5 (near normal)',
      'Current drought monitor category: None (D0 or better)',
      'Projected precipitation change by 2050: +2% to +4% (slightly wetter)',
      'Subsidence risk from soil shrink/swell: Minimal',
    ],
    dataSource: 'USDA Palmer Drought Severity Index / NOAA Climate Projections',
    lastUpdated: '2024-12-01T00:00:00Z',
    palmerDroughtIndex: -0.5,
    droughtMonitorCategory: 'NONE',
    projectedPrecipitationChange2050: 3,
    subsidenceRisk: 'LOW',
  },
  complianceScore: 78,
  stateContext: {
    stateCode: 'IL',
    stateName: 'Illinois',
    knownRisks: ['New Madrid Seismic Zone proximity', 'Tornado Alley location', 'Seasonal temperature extremes'],
    carrierCountTrend: 'STABLE',
    residualMarketUsage: 'LOW',
    compliance: {
      buildingCodeLevel: 'CURRENT',
      buildingCodeEnforcement: 4,
      rateRegulation: 'PRIOR_APPROVAL',
      mandatoryFloodZones: true,
      mandatoryWindstorm: false,
      earthquakeDisclosureRequired: false,
      naturalHazardDisclosure: true,
      sinkholeDisclosure: false,
      residualMarketPrograms: [],
    },
    scoreModifiers: {
      flood: 0,
      fire: 0,
      wind: 2,
      earthquake: 3,
      compliance: 1,
    },
  },
  generatedAt: '2024-12-01T00:00:00Z',
  cacheTtlSeconds: 7200,
}

export const dummyInsuranceEstimate: InsuranceCostEstimate = {
  propertyId: DUMMY_ID,
  estimatedAnnualTotal: 3420,
  estimatedMonthlyTotal: 285,
  confidenceLevel: 'MEDIUM',
  coverages: [
    {
      type: 'HOMEOWNERS',
      required: true,
      averageAnnualPremium: 1850,
      lowEstimate: 1500,
      highEstimate: 2200,
      notes: ['Covers dwelling, personal property, liability, and additional living expenses'],
    },
    {
      type: 'FLOOD',
      required: false,
      averageAnnualPremium: 450,
      lowEstimate: 300,
      highEstimate: 700,
      notes: ['Recommended even though property is in Zone X', 'NFIP Preferred Risk Policy may apply'],
    },
    {
      type: 'EARTHQUAKE',
      required: false,
      averageAnnualPremium: 720,
      lowEstimate: 500,
      highEstimate: 1100,
      notes: ['Strongly recommended due to proximity to New Madrid Seismic Zone', 'High deductible (10-15%) is typical'],
    },
    {
      type: 'WIND_HURRICANE',
      required: false,
      averageAnnualPremium: 400,
      lowEstimate: 250,
      highEstimate: 600,
      notes: ['Covers wind and tornado damage not included in standard HO policy'],
    },
  ],
  keyRiskFactors: [
    'Proximity to New Madrid Seismic Zone increases earthquake insurance cost',
    'Tornado Alley location affects wind coverage pricing',
    'Home age (1995) is within acceptable range for most carriers',
  ],
  recommendations: [
    'Bundle homeowners and flood policies for potential 10-15% discount',
    'Consider earthquake coverage given elevated seismic risk',
    'Install storm shutters or impact-resistant roofing for wind premium discounts',
    'Maintain a home inventory for faster claims processing',
  ],
  disclaimers: [
    'Estimates are based on publicly available data and may differ from actual quotes.',
    'Final premiums depend on carrier underwriting, credit score, and claims history.',
    'This is not an offer of insurance. Contact a licensed agent for binding quotes.',
  ],
  generatedAt: '2024-12-01T00:00:00Z',
}

export const dummyInsurability: InsurabilityStatus = {
  propertyId: DUMMY_ID,
  isInsurable: true,
  difficultyLevel: 'MODERATE',
  potentialIssues: [
    'Earthquake coverage may be limited to specialty carriers',
    'Some carriers may require wind/hail deductible in tornado-prone area',
    'Roof age inspection may be required if roof is original (1995)',
  ],
  recommendedActions: [
    'Obtain a 4-point inspection (roof, electrical, plumbing, HVAC)',
    'Document any recent roof replacement or upgrades',
    'Get multiple quotes from carriers active in Illinois',
    'Consider surplus lines carriers for earthquake coverage',
  ],
  overallInsurabilityScore: 42,
  categoryScores: {
    flood:      { score: 30, level: 'MODERATE', activeCarrierCount: 8 },
    fire:       { score: 25, level: 'LOW',      activeCarrierCount: 10 },
    wind:       { score: 45, level: 'MODERATE', activeCarrierCount: 7 },
    earthquake: { score: 55, level: 'HIGH',     activeCarrierCount: 4 },
    crime:      { score: 38, level: 'MODERATE', activeCarrierCount: 9 },
  },
}

export const dummyCarriers: CarriersResult = {
  propertyId: DUMMY_ID,
  carriers: [
    {
      id: 'carrier-1',
      name: 'State Farm',
      amBestRating: 'A++',
      writingStatus: 'ACTIVELY_WRITING',
      coverageTypes: ['HOMEOWNERS', 'FLOOD', 'UMBRELLA'],
      avgPremiumModifier: 0.95,
      statesLicensed: ['IL'],
      specialties: ['Midwest homeowners', 'Bundle discounts'],
      notes: 'Largest homeowner insurer in Illinois. Competitive rates for low-to-moderate risk.',
      appetiteSource: 'CARRIER_API',
      appetiteConfidence: 'HIGH',
      appetiteUpdatedAt: '2024-12-01T00:00:00.000Z',
    },
    {
      id: 'carrier-2',
      name: 'Allstate',
      amBestRating: 'A+',
      writingStatus: 'ACTIVELY_WRITING',
      coverageTypes: ['HOMEOWNERS', 'FLOOD', 'WIND_HURRICANE'],
      avgPremiumModifier: 1.02,
      statesLicensed: ['IL'],
      specialties: ['Claim forgiveness', 'New home discounts'],
      notes: 'Strong presence in Illinois. Offers deductible rewards program.',
      appetiteSource: 'INFERRED',
      appetiteConfidence: 'LOW',
      appetiteUpdatedAt: '2024-12-01T00:00:00.000Z',
    },
    {
      id: 'carrier-3',
      name: 'Country Financial',
      amBestRating: 'A+',
      writingStatus: 'ACTIVELY_WRITING',
      coverageTypes: ['HOMEOWNERS', 'UMBRELLA'],
      avgPremiumModifier: 0.92,
      statesLicensed: ['IL'],
      specialties: ['Illinois-based carrier', 'Farm & rural properties'],
      notes: 'Headquartered in Bloomington, IL. Excellent local claims service.',
      appetiteSource: 'INFERRED',
      appetiteConfidence: 'LOW',
      appetiteUpdatedAt: '2024-12-01T00:00:00.000Z',
    },
    {
      id: 'carrier-4',
      name: 'GeoVera Insurance',
      amBestRating: 'A-',
      writingStatus: 'LIMITED',
      coverageTypes: ['EARTHQUAKE'],
      avgPremiumModifier: 1.15,
      statesLicensed: ['IL'],
      specialties: ['Earthquake coverage specialist'],
      notes: 'One of the few carriers offering standalone earthquake policies in the Midwest.',
      appetiteSource: 'AGGREGATOR',
      appetiteConfidence: 'MEDIUM',
      appetiteUpdatedAt: '2024-12-01T00:00:00.000Z',
    },
  ],
  marketCondition: 'MODERATE',
  lastUpdated: '2024-12-01T00:00:00Z',
}

export const dummyPublicData: PropertyPublicData = {
  propertyId: DUMMY_ID,
  images: [
    {
      url: 'https://api.mapbox.com/styles/v1/mapbox/satellite-streets-v12/static/-89.6501,39.7817,16,0,0/800x600?access_token=PLACEHOLDER',
      source: 'Mapbox Satellite',
      caption: 'Satellite view of 742 Evergreen Terrace, Springfield, IL',
      type: 'satellite',
    },
  ],
  taxRecords: {
    assessedValue: 310000,
    taxAmount: 6820,
    taxYear: 2024,
    landValue: 65000,
    improvementValue: 245000,
    taxRate: 2.2,
  },
  saleHistory: [
    {
      date: '2021-06-15',
      price: 340000,
      pricePerSqFt: 158,
      seller: null,
      buyer: null,
    },
    {
      date: '2015-09-20',
      price: 265000,
      pricePerSqFt: 123,
      seller: null,
      buyer: null,
    },
  ],
  nearbyAmenities: [
    { name: 'Springfield Elementary School', type: 'school', distance: 0.4, rating: 4.2 },
    { name: 'Memorial Medical Center', type: 'hospital', distance: 2.1, rating: 4.5 },
    { name: 'Fire Station #7', type: 'fire_station', distance: 1.3, rating: null },
    { name: 'Washington Park', type: 'park', distance: 0.6, rating: 4.3 },
    { name: 'County Market', type: 'grocery', distance: 0.9, rating: 4.0 },
  ],
  listingData: {
    zestimate: 392000,
    rentEstimate: 2100,
    daysOnMarket: null,
    listingStatus: 'off_market',
    listPrice: null,
    pricePerSqFt: 179,
    description: null,
    features: ['Central Air', 'Attached Garage', 'Hardwood Floors', 'Fireplace', 'Fenced Yard'],
    yearRenovated: null,
    stories: 2,
    garage: '2-car attached',
    heating: 'Forced Air / Gas',
    cooling: 'Central Air',
    roofType: 'Asphalt Shingle',
    foundation: 'Poured Concrete',
    exteriorMaterial: 'Vinyl Siding',
    hoaFee: null,
  },
  walkScore: 62,
  transitScore: 28,
  neighborhoodMedianValue: 275000,
  neighborhoodMedianRent: 1450,
  lastUpdated: '2024-12-01T00:00:00Z',
}
